# Generated by Django 3.0.3 on 2023-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0002_auto_20230604_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='type',
            field=models.CharField(choices=[('CET4', 'CET4'), ('CET6', 'CET6')], default='CET4', max_length=129, verbose_name='考试类别'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('2', 'general'), ('1', 'easy')], max_length=10, verbose_name='等级'),
        ),
    ]
