# Generated by Django 3.0.3 on 2023-06-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0003_auto_20230623_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='题目')),
                ('answer', models.CharField(max_length=100, verbose_name='学生答案')),
                ('level', models.CharField(choices=[('3', 'difficult'), ('1', 'easy'), ('2', 'general')], max_length=10, verbose_name='等级')),
                ('totalScore', models.IntegerField(default=1, verbose_name='总分')),
                ('score', models.IntegerField(default=0, verbose_name='学生得分')),
            ],
            options={
                'verbose_name': '主观题库',
                'verbose_name_plural': '主观题库',
                'db_table': 'subQuestion',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='objectGrade',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='grade',
            name='subjectGrade',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('1', 'easy'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
        migrations.AddField(
            model_name='paper',
            name='sqid',
            field=models.ManyToManyField(to='signUp.SubQuestion'),
        ),
    ]
