# Generated by Django 4.2.1 on 2023-06-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0005_student_id_no_student_id_type_student_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplace',
            name='Ispay',
            field=models.CharField(default=0, max_length=20, verbose_name='支付状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('2', 'general'), ('3', 'difficult')], max_length=10, verbose_name='等级'),
        ),
    ]
