# Generated by Django 3.0.3 on 2023-06-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0008_auto_20230626_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('3', 'difficult'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('3', 'difficult'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
    ]
