# Generated by Django 3.0.3 on 2023-06-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0009_auto_20230627_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('2', 'general'), ('1', 'easy')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('2', 'general'), ('1', 'easy')], max_length=10, verbose_name='等级'),
        ),
    ]
