# Generated by Django 3.0.3 on 2023-06-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0010_auto_20230627_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplace',
            name='Ispay',
            field=models.CharField(default='0', max_length=20, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='student',
            name='ID_NO',
            field=models.CharField(default=None, max_length=20, verbose_name='证据号码'),
        ),
        migrations.AddField(
            model_name='student',
            name='ID_type',
            field=models.CharField(choices=[('中华人民共和国居民身份证', '中华人民共和国居民身份证'), ('港澳居民来往内地通行证', '港澳居民来往内地通行证'), ('台湾居民来往大陆通行证', '台湾居民来往大陆通行证')], default='中华人民共和国居民身份证', max_length=20, verbose_name='证件类型'),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default=None, max_length=20, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.CharField(default=None, max_length=20, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('1', 'easy'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='subquestion',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('1', 'easy'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
    ]
