# Generated by Django 4.2.1 on 2023-06-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0003_alter_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('3', 'difficult'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
    ]
