# Generated by Django 4.2.1 on 2023-06-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0004_alter_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ID_NO',
            field=models.CharField(default=None, max_length=20, verbose_name='证据号码'),
        ),
        migrations.AddField(
            model_name='student',
            name='ID_type',
            field=models.CharField(choices=[('中华人民共和国居民身份证', '中华人民共和国居民身份证'), ('港澳居民来往内地通行证', '港澳居民来往内地通行证'), ('台湾居民来往大陆通行证', '台湾居民来往大陆通行证')], default='中华人民共和国居民身份证', max_length=20, verbose_name='证件类型'),
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default=None, max_length=20, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.CharField(default=None, max_length=20, verbose_name='备注'),
        ),
    ]
